### PR TITLE
Gentx Kleomedes

### PR DESCRIPTION
**Pull request by kleomedes**

### CODE REVIEW

**Comment by codehans** [comment]
@kleomedes I don't see the validator address `kujiravaloper17200mes7mplx33x8gcegkurqmz35d7v4lydt6f` in the validators.json snapshot. have you changed it from testnet?

**Comment by kleomedes** [comment]
> @kleomedes I don't see the validator address `kujiravaloper17200mes7mplx33x8gcegkurqmz35d7v4lydt6f` in the validators.json snapshot. have you changed it from testnet?

I prefer not to reuse the same keys on different nodes, is that a problem?
 On harpoon-4 this is our address 'kujiravaloper1gz2c6rkwf9quztvwynwr2hsa9lmldnjlk4j5gd'

**Comment by kleomedes** [comment]
> 

https://testnets.cosmosrun.info/kujira/tx/93AEA44FD1DFC21903F9364C6BA931F7234FFA081042E4A50D2763582315D1CB

**Comment by kleomedes** [comment]
> > 
> 
> https://testnets.cosmosrun.info/kujira/tx/93AEA44FD1DFC21903F9364C6BA931F7234FFA081042E4A50D2763582315D1CB

@codehans let me know if this tx suffice.

**Pull request merged**
