### PR TITLE
Create gentx-forgottensemicolon.json

### PR DESCRIPTION
**Pull request by mmc6185**
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"forgottensemicolon","identity":"893143882D719A8ADB0F4C165D2688ABD5173AA3","website":"https://forum.rues.info/index.php","security_contact":"https://linktr.ee/forgottensemicolon","details":"RuesCommunity"},"commission":{"rate":"0.100000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"kujira1xuy0enuzvn38et2pjhd256znjnp84ssyu7t93y","validator_address":"kujiravaloper1xuy0enuzvn38et2pjhd256znjnp84ssymtckdt","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"4mG+iw8+J/HlVc8ussudBMhM+9oJQBDTkwm2o+G+xGw="},"value":{"denom":"ukuji","amount":"99000000"}}],"memo":"ce422efa5783c71ee0dff70a8a5b06a12fe697ec@38.242.227.183:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Awr1BclKRCFShrGeuXoWlWnULOQDUkP4D6EuQ4ihf18w"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":["LsSDSkbhRSCcKvQepmVpiZiRf4uKvQCk4hmBYpPq9MwAWJRdku1vzCRGpEF8/56fMXqAl7DnfSmHdRUIoa+WNA=="]}

### CODE REVIEW

**Comment by codehans** [comment]
@mmc6185 could you please sign a tx from `kujiravaloper1xuy0enuzvn38et2pjhd256znjnp84ssymtckdt` to `kujiravaloper1evpgnzchgfyzkpdktcxdf4gqu52xqjt3txw6gr` to prove move of address

**Comment by mmc6185** [comment]
> @mmc6185 could you please sign a tx from `kujiravaloper1xuy0enuzvn38et2pjhd256znjnp84ssymtckdt` to `kujiravaloper1evpgnzchgfyzkpdktcxdf4gqu52xqjt3txw6gr` to prove move of address

I updated my genxt

**Comment by codehans** [comment]
> > @mmc6185 could you please sign a tx from `kujiravaloper1xuy0enuzvn38et2pjhd256znjnp84ssymtckdt` to `kujiravaloper1evpgnzchgfyzkpdktcxdf4gqu52xqjt3txw6gr` to prove move of address
> 
> I updated my gentx

@mmc6185 did you push the change? the PR is still the same

**Comment by mmc6185** [comment]
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"forgottensemicolon","identity":"893143882D719A8ADB0F4C165D2688ABD5173AA3","website":"https://forum.rues.info/index.php","security_contact":"https://linktr.ee/forgottensemicolon","details":"RuesCommunity"},"commission":{"rate":"0.100000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"kujira1xuy0enuzvn38et2pjhd256znjnp84ssyu7t93y","validator_address":"kujiravaloper1xuy0enuzvn38et2pjhd256znjnp84ssymtckdt","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"4mG+iw8+J/HlVc8ussudBMhM+9oJQBDTkwm2o+G+xGw="},"value":{"denom":"ukuji","amount":"99000000"}}],"memo":"ce422efa5783c71ee0dff70a8a5b06a12fe697ec@38.242.227.183:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Awr1BclKRCFShrGeuXoWlWnULOQDUkP4D6EuQ4ihf18w"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":["LsSDSkbhRSCcKvQepmVpiZiRf4uKvQCk4hmBYpPq9MwAWJRdku1vzCRGpEF8/56fMXqAl7DnfSmHdRUIoa+WNA=="]}

**Pull request merged**
