### PR TITLE
Add gentx for vbloher validator

### PR DESCRIPTION
**Pull request by vbloher**

### CODE REVIEW

**Comment by codehans** [comment]
@vbloher could you please provide a tx hash sending tokens from `kujiravaloper1aaq8t0ttwcqpx8r73yx8gny3andrtrkt7hpmw7` to `kujiravaloper1yafsywsluqdvlhtp30tcdhw496vg6ey3zs4u84` to confirm the change of address please

**Comment by vbloher** [comment]
@codehans could you clarify what I need to do because you have specified the valoper addresses above

**Comment by vbloher** [comment]
I just added a key different from what I used in the testnet and generated gentx

**Comment by vbloher** [comment]
Sent some demo tokens
https://kujira.explorers.guru/transaction/320ADD45045835DBCCF703626295D51B6867431299FFD0FD8B6FEE4AC648C374

**Pull request merged**
